version: "3.3"
services:
  siri-xlite:
    build: .
    image: "siri-xlite"
    depends_on:
      - "mongodb"
    ports:
      - "8443:8443"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
