siri-xlite:
  port: 8443

  lines-discovery:
    max-age: 30
    s-maxage: 3600
  stoppoints-discovery:
    max-age: 30
    s-maxage: 3600
  stop-monitoring:
    max-age: 30
    s-maxage: 600
  estimated-timetable:
    max-age: 30
    s-maxage: 600
  estimated-vehicle-journey:
    max-age: 30
    s-maxage: 60

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.mongodb: INFO

spring:
  data:
    mongodb:
      database: siri

infinispan:
  embedded:
    enabled: false
    config-xml: infinispan.xml
