siri:
  port: 8080
  version: 2.0:FR-IDF-2.4
  participantRef: default
  producerDomain: default
  producerName: default

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.mongodb: INFO

spring:
  data:
    mongodb:
      database: siri


infinispan:
  embedded:
    enabled: false
    config-xml: infinispan.xml
