version: "3.3"
services:
  nuster:
    build:
      context: "../"
      dockerfile: "docker/nuster/Dockerfile"
    depends_on:
      - "siri-xlite"
    ports:
      - "80:80"
      - "8443:8443"
  siri-xlite:
    build:
      context: "../"
      dockerfile: "docker/siri-xlite/Dockerfile"
    depends_on:
      - "mongodb"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
